const dark = document.querySelector(".btn-dark-mode");
const body = document.querySelector("body");
const pg1 = document.querySelector(".pg-1");
const pg2 = document.querySelector(".pg-2");
const pg3 = document.querySelector(".pg-3");
const letras = document.querySelectorAll("li");
const button = document.querySelectorAll("button");
const login = document.querySelector(".login");
const logo = document.querySelector("#logo");
const pgh = document.querySelector(".pg-1-1");
const ptexthome = document.querySelector(".p-text-home");
const navbar = document.querySelector(".nav-bar");
const register = document.querySelector(".register");
const badage = document.querySelector(".badage");
const header = document.querySelector(".header");
const home = document.querySelector(".Home");
const Privacy = document.querySelector(".Privacy");
const Terms = document.querySelector(".Terms");
const block = document.querySelector(".block");
const pr1 = document.querySelector(".pr-1");
const pr2 = document.querySelector(".pr-2");
const pr3 = document.querySelector(".pr-3");
const pr4 = document.querySelector(".pr-4");
const boxpg3 = document.querySelector(".box-pg-3");
const fbtn = document.querySelector(".button-final");

dark.onclick = () => {
  dark.classList.toggle("dark");
  body.classList.toggle("dark");
  pg1.classList.toggle("dark");
  pg2.classList.toggle("dark");
  pg3.classList.toggle("dark");
  login.classList.toggle("dark");
  badage.classList.toggle("dark");
  ptexthome.classList.toggle("dark");
  pgh.classList.toggle("dark");
  register.classList.toggle("dark");
  header.classList.toggle("dark");
  home.classList.toggle("dark");
  Privacy.classList.toggle("dark");
  Terms.classList.toggle("dark");
  block.classList.toggle("dark");
  pr1.classList.toggle("dark");
  pr2.classList.toggle("dark");
  pr3.classList.toggle("dark");
  pr4.classList.toggle("dark");
  boxpg3.classList.toggle("dark");
  fbtn.classList.toggle("dark");
};
